name: echofetch
description: "A sustainable waste management solution offering at-home waste pickup, smart sorting, and responsible recycling."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

#----------Packages----------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  intl: ^0.18.0
  url_launcher: ^6.2.6
  uuid: ^4.3.3
  shortid: ^0.1.2
  flutter_native_splash: ^2.4.0
  smooth_page_indicator: ^1.1.0

  # Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  # Fonts
  google_fonts: ^6.1.0

  # State Management
  get: ^4.6.6
  get_storage: ^2.1.1

  # Chatbot
  dash_chat_2: ^0.0.20
  google_generative_ai: ^0.3.1

  # Others
  easy_stepper: ^0.8.3
  font_awesome_flutter: ^10.7.0
  like_button: ^2.0.5
  story_view: ^0.16.5
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5
  badges: ^3.1.2

  
#----------Dev Packages----------#
dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

#----------App Launcher icon----------#
flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/icons/launcher-icon.png"
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

#----------Local Assets----------#
  assets:
    - assets/images/onboarding/
    - assets/images/authentication/
    - assets/images/pickup/
    - assets/images/rewards/
    - assets/images/shop/
    - assets/images/
    - assets/logos/
    - assets/icons/


  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
